# Generated by Django 5.0.6 on 2024-07-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Install',
            fields=[
                ('external_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('access_token', models.TextField()),
                ('campaign', models.TextField(blank=True, null=True)),
                ('campaign_id', models.PositiveIntegerField(blank=True, null=True)),
                ('campaign_unique_clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('conversions', models.PositiveIntegerField(blank=True, null=True)),
                ('country_flag', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('os', models.TextField(blank=True, null=True)),
                ('os_version', models.TextField(blank=True, null=True)),
                ('sales', models.PositiveIntegerField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('sub_id', models.TextField(blank=True, null=True)),
                ('sub_id_1', models.TextField(blank=True, null=True)),
                ('sub_id_2', models.TextField(blank=True, null=True)),
                ('sub_id_3', models.TextField(blank=True, null=True)),
                ('sub_id_5', models.TextField(blank=True, null=True)),
                ('sub_id_6', models.TextField(blank=True, null=True)),
                ('sub_id_7', models.TextField(blank=True, null=True)),
                ('sub_id_8', models.TextField(blank=True, null=True)),
                ('sub_id_9', models.TextField(blank=True, null=True)),
                ('sub_id_10', models.TextField(blank=True, null=True)),
                ('sub_id_11', models.TextField(blank=True, null=True)),
                ('sub_id_12', models.TextField(blank=True, null=True)),
                ('sub_id_13', models.TextField(blank=True, null=True)),
                ('sub_id_14', models.TextField(blank=True, null=True)),
                ('sub_id_15', models.TextField(blank=True, null=True)),
                ('sub_id_16', models.TextField(blank=True, null=True)),
                ('sub_id_17', models.TextField(blank=True, null=True)),
                ('sub_id_18', models.TextField(blank=True, null=True)),
                ('sub_id_19', models.TextField(blank=True, null=True)),
                ('sub_id_20', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
