# Generated by Django 5.0.6 on 2024-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('key_id', models.TextField(blank=True, null=True)),
                ('team_id', models.TextField(blank=True, null=True)),
                ('key', models.FileField(upload_to='keys/')),
                ('bundle', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
