# Generated by Django 5.0.6 on 2024-07-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0003_alter_application_bundle_alter_application_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='install',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installs', to='installs.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='bundle',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Бандл'),
        ),
    ]
