# Generated by Django 5.0.6 on 2024-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0004_install_application_alter_application_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='alert',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='push',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
