# Generated by Django 5.0.6 on 2024-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0005_push_alert_push_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='push',
            old_name='alert',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='push',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='install',
            name='access_token',
        ),
        migrations.AddField(
            model_name='install',
            name='stream',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='stream_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_25',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_26',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_27',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_28',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_29',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='install',
            name='sub_id_30',
            field=models.TextField(blank=True, null=True),
        ),
    ]
