# Generated by Django 5.0.6 on 2024-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0006_rename_alert_push_text_rename_topic_push_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='launch_image',
            field=models.ImageField(blank=True, null=True, upload_to='launch_images'),
        ),
    ]
