# Generated by Django 5.0.6 on 2024-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0007_push_launch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='install',
            name='status',
            field=models.CharField(default='Install', max_length=64),
        ),
    ]
