# Generated by Django 5.0.6 on 2024-08-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0011_remove_push_day_remove_push_time_push_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='campaign_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID Кампании'),
        ),
    ]
