# Generated by Django 5.0.6 on 2024-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=128, verbose_name='Название')),
                ('fbtool_id', models.PositiveBigIntegerField(verbose_name='Fbtool ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('cookie', models.JSONField(blank=True, null=True)),
                ('group_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('is_restricted', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('proxy', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('value', models.FloatField(default=0, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('creative', models.JSONField(blank=True, null=True)),
                ('effective_status', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_status', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('timezone', models.CharField(max_length=64, verbose_name='Таймзона')),
                ('currency', models.CharField(max_length=8, verbose_name='Валюта')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('adspaymentcycle', models.JSONField(blank=True, null=True)),
                ('adtrust_dsl', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount_spent', models.PositiveIntegerField(blank=True, null=True)),
                ('current_unbilled_spend', models.JSONField(blank=True, null=True)),
                ('disable_reason', models.IntegerField(blank=True, null=True)),
                ('funding_source_details', models.JSONField(blank=True, null=True)),
                ('fbtool_id', models.TextField(blank=True, null=True)),
                ('is_prepay_account', models.BooleanField(blank=True, null=True)),
                ('next_bill_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.BigIntegerField(blank=True, null=True)),
                ('prepay_account_balance', models.JSONField(blank=True, null=True)),
                ('spend_cap', models.IntegerField(blank=True, null=True)),
                ('timezone_offset_hours_utc', models.IntegerField(blank=True, null=True)),
                ('viewable_business', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_status', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Расход')),
                ('clicks', models.PositiveIntegerField(verbose_name='Клики')),
                ('definitive', models.BooleanField(default=False, verbose_name='Окончательный вариант')),
                ('cost_per_unique_click', models.FloatField(null=True)),
                ('cpc', models.FloatField(null=True)),
                ('cpm', models.FloatField(null=True)),
                ('ctr', models.FloatField(null=True)),
                ('impressions', models.PositiveIntegerField(null=True)),
                ('objective', models.TextField(null=True)),
                ('quality_score_ectr', models.PositiveIntegerField(null=True)),
                ('quality_score_ecvr', models.PositiveIntegerField(null=True)),
                ('quality_score_organic', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Доход')),
                ('clicks', models.PositiveIntegerField(verbose_name='Клики')),
                ('purchases', models.PositiveIntegerField(verbose_name='Покупки')),
                ('registrations', models.PositiveIntegerField(verbose_name='Регистрации')),
                ('sub1', models.TextField(verbose_name='sub1')),
                ('sub2', models.TextField(verbose_name='sub2')),
                ('sub3', models.TextField(verbose_name='sub3')),
                ('sub5', models.TextField(verbose_name='sub5')),
                ('sub6', models.TextField(verbose_name='sub6')),
                ('sub7', models.TextField(verbose_name='sub7')),
                ('pixel', models.BigIntegerField(verbose_name='Пиксель')),
                ('fbclid', models.TextField(verbose_name='fbclid')),
                ('bundle_id', models.TextField(verbose_name='bundleid')),
                ('definitive', models.BooleanField(default=False, verbose_name='Окончательный вариант')),
            ],
        ),
    ]
