# Generated by Django 5.0.6 on 2024-06-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Баер'),
        ),
        migrations.AddField(
            model_name='ad',
            name='adset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.adset', verbose_name='Адсет'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='adminapp.account', verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='adminapp.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='adset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.campaign', verbose_name='Кампания'),
        ),
        migrations.AddField(
            model_name='cost',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to=settings.AUTH_USER_MODEL, verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='action',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='adminapp.cost', verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to=settings.AUTH_USER_MODEL, verbose_name='Баер'),
        ),
    ]
