# Generated by Django 5.0.6 on 2024-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_cost_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Клики'),
        ),
    ]
