# Generated by Django 5.0.6 on 2024-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_cost_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Кабинет удалён'),
        ),
    ]
