# Generated by Django 5.0.6 on 2024-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_cabinet_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='bundle_id',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='fbclid',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='pixel',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='purchases',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='registrations',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='sub5',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='sub6',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='sub7',
        ),
        migrations.AddField(
            model_name='revenue',
            name='campaign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='campaign_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='campaign_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='campaign_unique_clicks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='conversions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='os_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='os_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='sub_id_9',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
