# Generated by Django 5.0.6 on 2024-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_revenue_bundle_id_remove_revenue_fbclid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='date',
        ),
        migrations.AddField(
            model_name='revenue',
            name='datetime',
            field=models.DateField(null=True, verbose_name='Дата и время'),
        ),
    ]
