# Generated by Django 5.0.6 on 2024-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_revenue_date_revenue_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
    ]
