# Generated by Django 5.0.6 on 2024-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_revenue_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='sub_id_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
