# Generated by Django 5.0.6 on 2024-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_revenue_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='amount_USD',
            field=models.FloatField(null=True, verbose_name='Расход USD'),
        ),
    ]
