# Generated by Django 5.0.6 on 2024-07-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_cost_amount_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='adtrust_dsl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='amount_spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='spend_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='quality_score_ectr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='quality_score_ecvr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='quality_score_organic',
            field=models.FloatField(null=True),
        ),
    ]
