# Generated by Django 5.0.6 on 2024-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_cabinet_adtrust_dsl_alter_cabinet_amount_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('type', models.CharField(max_length=16, verbose_name='Тип')),
            ],
        ),
    ]
