# Generated by Django 5.0.6 on 2024-07-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='business',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
