# Generated by Django 5.0.6 on 2024-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_cabinet_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='finished',
            field=models.BooleanField(default=True, verbose_name='Закончен'),
        ),
    ]
