# Generated by Django 5.0.6 on 2024-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_update_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='type',
            field=models.TextField(verbose_name='Тип'),
        ),
    ]
