# Generated by Django 5.0.6 on 2024-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_update_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
