# Generated by Django 5.0.6 on 2024-07-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_account_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
