# Generated by Django 5.0.6 on 2024-07-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_update_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
