# Generated by Django 5.0.6 on 2024-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_account_is_deleted_alter_cabinet_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
