# Generated by Django 5.0.6 on 2024-07-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_account_bm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
