# Generated by Django 5.0.6 on 2024-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_cost_campaign_alter_cost_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsPerMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, verbose_name='Минута')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество запросов')),
            ],
        ),
    ]
