# Generated by Django 5.0.6 on 2024-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_requestsperminute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsperminute',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Минута'),
        ),
    ]
