# Generated by Django 5.0.6 on 2024-08-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_alter_update_datetime_alter_update_finished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestsPerMinute',
        ),
    ]
